# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-8MhflF2JLdmNv5P5Dvew7ble86xJVcg

***1.Install required Python libraries***
"""

!pip install yfinance numpy pandas scipy matplotlib

"""***2.We define a 30-stock universe across sectors.***"""

import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import minimize

tickers = [
    "AAPL","MSFT","GOOGL","AMZN","TSLA",
    "NVDA","META","NFLX","AMD","INTC",
    "JPM","BAC","GS","C","WFC",
    "JNJ","PFE","MRK","UNH","ABBV",
    "XOM","CVX","COP","OXY","BP",
    "PG","KO","PEP","WMT","DIS"
]

"""***3.Download historical stock data using Yahoo Finance API***"""

start_date = "2026-01-01"
end_date = pd.Timestamp.today().strftime('%Y-%m-%d')

data = yf.download(tickers, start=start_date, end=end_date)["Close"]


data = data.dropna(axis=1)

returns = data.pct_change().dropna()

data.head()

"""***4.We rank stocks by a simplified Sharpe ratio and select top 10.***"""

mean_returns = returns.mean()
std_returns = returns.std()

sharpe_like = mean_returns / std_returns

top10_tickers = sharpe_like.sort_values(ascending=False).head(10).index.tolist()

print("Selected 10 stocks:", top10_tickers)

"""***5.We optimize portfolio weights using Mean-Variance Optimization.***"""

selected_returns = returns[top10_tickers]

mean_returns = selected_returns.mean()
cov_matrix = selected_returns.cov()

def portfolio_performance(weights):
    ret = np.dot(weights, mean_returns) * 252
    vol = np.sqrt(np.dot(weights.T, np.dot(cov_matrix * 252, weights)))
    return ret, vol

def negative_sharpe(weights):
    ret, vol = portfolio_performance(weights)
    return -ret / vol

num_assets = len(top10_tickers)
init_guess = num_assets * [1./num_assets]

bounds = tuple((0.05, 0.5) for _ in range(num_assets))
constraints = ({'type': 'eq', 'fun': lambda x: np.sum(x) - 1})

result = minimize(
    negative_sharpe,
    init_guess,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

weights = result.x

for i, t in enumerate(top10_tickers):
    print(t, ":", round(weights[i], 3))

"""***6.Rolling Window***"""

rolling_returns = []

window_size = 5

def optimize_portfolio(mean_returns_df, cov_matrix_df):
    def negative_sharpe_local(weights):
        ret = np.dot(weights, mean_returns_df) * 252
        vol = np.sqrt(np.dot(weights.T, np.dot(cov_matrix_df * 252, weights)))
        return -ret / vol

    num_assets_local = len(mean_returns_df)
    init_guess_local = num_assets_local * [1./num_assets_local]

    # Using global bounds and constraints already defined in 09EYLQ3EzS03
    result_local = minimize(
        negative_sharpe_local,
        init_guess_local,
        method="SLSQP",
        bounds=bounds,
        constraints=constraints
    )
    return result_local.x

for i in range(window_size, len(returns)):

    window_data = returns.iloc[i-window_size:i][top10_tickers]

    mean_ret = window_data.mean()
    cov_mat = window_data.cov()

    weights = optimize_portfolio(mean_ret, cov_mat)

    next_day_return = np.dot(weights, returns.iloc[i][top10_tickers])

    rolling_returns.append(next_day_return)

rolling_returns = pd.Series(rolling_returns)

"""***7.Compare portfolio performance with S&P 500 benchmark***"""

sp500 = yf.download("^GSPC", start=start_date, end=end_date)["Close"]
sp500_returns = sp500.pct_change().dropna()


min_len = min(len(rolling_returns), len(sp500_returns))
rolling_returns = rolling_returns[-min_len:]
sp500_returns = sp500_returns[-min_len:]

cum_model = (1 + rolling_returns).cumprod()
cum_sp500 = (1 + sp500_returns).cumprod()

plt.figure(figsize=(10,6))
plt.plot(cum_model, label="Model")
plt.plot(cum_sp500.values, label="S&P 500")
plt.legend()
plt.title("2026 YTD Performance Comparison")
plt.show()

"""***8.Rolling Performance***"""

plt.figure(figsize=(10,6))
plt.plot((1 + rolling_returns).cumprod())
plt.title("Rolling Portfolio Performance (2026)")
plt.xlabel("Time Steps")
plt.ylabel("Cumulative Return")
plt.show()

"""***I used Modern Portfolio Theory to select and optimize a 10-stock portfolio, maximizing Sharpe ratio, and compared it with the S&P 500 using historical backtesting.***"""

plt.savefig("portfolio.png")